### ISSUE TITLE
Not available on Intel Nuc

### ISSUE THREAD

**Issue by lukasmd1989** [adamoutler/HassOSConfigurator#1]
Hi, i tried to install this on my Hassio instance on an Intel Nuc, but unfortunately I get following message: This add-on is not available on your system. "

**Comment by adamoutler** [comment]
Hi crush, which partition is used for the boot partition on Nuc?  /dev/sda1?

**Comment by nickrout** [comment]
I am getting this on a virtualbox instance,

**Comment by nickrout** [comment]
Is this not available on no pi OSes?
```
"arch": ["armhf", "armv7", "aarch64"],
```

**Comment by adamoutler** [comment]
Not currently.  Will it work?  You can git pull the repo into your add-ons and add your arch. If it works I can support it.

**Comment by alexdelprete** [comment]
Same problem on an Intel NUC with an SSD drive, that is not mounted as sda1 sdb1 but like this:

```
/dev/nvme0n1p8 on /share type ext4 (rw,relatime)
/dev/nvme0n1p8 on /config type ext4 (rw,relatime)
/dev/nvme0n1p8 on /backup type ext4 (rw,relatime)
/dev/nvme0n1p8 on /addons type ext4 (rw,relatime)
/dev/nvme0n1p8 on /data type ext4 (rw,relatime)
/dev/nvme0n1p8 on /ssl type ext4 (rw,relatime)
/dev/nvme0n1p8 on /media type ext4 (rw,relatime)
/dev/nvme0n1p8 on /etc/asound.conf type ext4 (ro,relatime)
/dev/nvme0n1p8 on /run/audio type ext4 (ro,relatime)
/dev/nvme0n1p8 on /etc/hosts type ext4 (rw,relatime)
/dev/nvme0n1p8 on /etc/hostname type ext4 (rw,relatime)
/dev/nvme0n1p8 on /etc/resolv.conf type ext4 (rw,relatime)
/dev/nvme0n1p8 on /etc/pulse/client.conf type ext4 (ro,relatime)
/dev/nvme0n1p8 on /var/log/journal type ext4 (ro,relatime)
```

These are the partitions:

```
nvme0n1                                    232.9G KINGSTON SA2000M8250G
├─nvme0n1p1                                   32M
├─nvme0n1p2                                   24M
├─nvme0n1p3              /sbin/docker-init   256M
├─nvme0n1p4                                   24M
├─nvme0n1p5                                  256M
├─nvme0n1p6                                    8M
├─nvme0n1p7                                   96M
└─nvme0n1p8              /var/log/journal  232.2G
```

Would be good to have this addon working also in non-standard cases like this. Maybe a configuration option to specify the partition would be a good idea, unless there’s a way to retrieve it automatically.

Thanks for any help on this.

(I also posted this in the forum: https://community.home-assistant.io/t/add-on-hassos-ssh-port-22222-configurator/264109/118?u=alexdelprete)

**Comment by adamoutler** [comment]
Yes.  This doesn't support nvme0n1p1. This is a separate issue all together.  Since there is no way for me to reproduce without hardware, I will accept a pull request.   You should fork the repo, add "nvme0n1p1" to config.json and run.sh in the locations where you see "sda1", and "mmcblk0p1".

**Comment by alexdelprete** [comment]
Thanks for the reply Adam, two questions:

1. Can I edit config.json and run.sh in the container instead of forking?
2. Could the name of the device be added as a config option? So that wouldn'r require a fork for special cases like these.

I'll try to make it work and report back.

**Comment by adamoutler** [comment]
You could, but it wouldn't help for contributing.  If you fork, then use the terminal addon and then git clone your repo to the /addons folder,, you can make changes and install from the local copy, then push your changes back whenever.  When you're ready, you can pull request to my repo.

**Comment by alexdelprete** [comment]
I forked it, modified run.sh accordingly, but in config.json I don't see anything relevant to partitions. So I only modify run.sh, correct?

If you can confirm only run.sh has to be modified, I will clone it locally, test it, and if it works I'll do a PR.

BTW, I noticed a small bug in this code (sdb1 was missing):

`mkdir /tmp/mmcblk0p1 /tmp/sda1 2> /dev/null`

**Comment by alexdelprete** [comment]
The patch worked fine. I just tested it on my NUC. PR submitted.

![image](https://user-images.githubusercontent.com/7027842/115162386-8cf65780-a0a3-11eb-9022-77644bb5a5d2.png)

**Comment by adamoutler** [comment]
Right.  There was an old version where I had to declare all partitions as devices so as to improve security rating.  That's no longer the case.  Sec rating is 1.

**Comment by adamoutler** [comment]
Thanks for the PR.
