### ISSUE TITLE
Seem to have to reinstall after every update of HA

### ISSUE THREAD

**Issue by Electronlibre2012** [adamoutler/HassOSConfigurator#12]
Hello,

after some time my media folder, where the usbstorage is mount, is growing, my snapshot is growing too.

I noticed thant the size of my snapshot where is normaly to 1,2Go, my snapshot is 4,8Go, what is my video recors from camera, about 3,6Go for a week + 1.2Go of normal snapshot.

Then i delete all my cam records and the new daily snapshot go down to 1,2Go.

So i check and my 2nd ssd disk is not mount anymore, means my records are saved to my HA disk (where HassOs is running, nvme disk of 240Go and not on my 2nd disk SSD Crucial 2To, i have a NUC8 I5).

So i start again the add-on and plug off then restart the unplug power for the 2nd time, after that all work as expected (but i cannot access hassos on 22222 port...) : i mean my usbstorage ssd is mount and even if i had 5Go of records, my snapshot is at about 1,2Go as expected.

I am the only one with this trouble please? i mean every new update of HA break the "created authorisations key in nvme0n1p1"?

Thanks

**Comment by adamoutler** [comment]
I've never heard of not experienced this.

**Comment by adamoutler** [comment]
I think you should take this to the HAOS project.   Once the key is installed, this is done.  Sounds like upgrades are pwning your setup.

**Comment by Electronlibre2012** [comment]
Thanks for your quick reply!

Ok...no way to understand what happened on my side...

yes thanks, sure the upgrades do something...

have a nice day
