### ISSUE TITLE
[SUGGESTION] Permit manually add the i2c values

### ISSUE THREAD

**Issue by hellresistor** [adamoutler/HassOSConfigurator#13]
Hello friend,
I am give a sugestion to upgrade the Addon about enabling i2c

I think will be very good exists an field to manually add values.
Some people needs add more parameters like

```
dtparam=i2c_arm=on
dtoverlay=i2c-rtc,ds1307,addr=0x68
dtoverlay=dwc2,dr_mode=host
```

hope you understand what i mean.

Thank you

**Comment by adamoutler** [comment]
Submit a pull request.  I can't theorize about how this will work.

**Comment by hellresistor** [comment]
updated ;)
