### ISSUE TITLE
Run on Startup.d Not starting

### ISSUE THREAD

**Issue by pickonedev** [adamoutler/HassOSConfigurator#16]
Hi!

When I try to start the addon, I get this error

`Can't create container from addon_1f3d020e_run_on_startup_addon: 409 Client Error for http+docker://localhost/v1.41/containers/create?name=addon_1f3d020e_run_on_startup_addon: Conflict ("Conflict. The container name "/addon_1f3d020e_run_on_startup_addon" is already in use by container "67e60a06525e67f5a0aa0639031d89b0989834b54199f238f456561f9dfbff74". You have to remove (or rename) that container to be able to reuse that name."`

First time when I start the addon, I was ok, it started, then I wanted to choose "Create example scripts in /config/startup/startup.d", it started again, all good, but after I unticked "Create example scripts in /config/startup/startup.d" and restarted the addon, all went bad. It is not starting anymore...

I have rebuilded the addon, reinstalled, restarted HA, still nothing...

In the end, after the addon will work properly, I want to achieve a mount of a drive to media folder. Can you explain me more how can I do that? All I know is that the partition I want to mount is sda1... I think I should write mount /dev/sda1 /media/hp-drive (the folder it is already created), but is this enough? And I think this shuold be in the homeassistant.sh  file, right? :-D

Any idea how to solve it? I'm a newbie...

**Comment by adamoutler** [comment]
Uninstall and reinstall

**Comment by pickonedev** [comment]
I made a completely shutdown after uninstall, then installed again. Worked. Thanks!

Can you please help me with the second part of the "issue" ?
I have a partition sda1 and I want to mount it to media/hp-drive, everytime HA reboots...
I made a file homeassistant.sh, and I putted into the config/startup/startup.d/
The content of the file is this

```
#! /bin/bash
mount /dev/sda1 /media/hp-drive
```

But it is not mounting the drive to that folder :-(
Checking the startup.d log, I get an error: 

```
executing
#############################################################################
###############/config/startup/startup.d/homeassistant.sh
###############Container: 0e93cfcca474: tmp/homeassistant.startup.sh
#############################################################################
mount: mounting /dev/sda1 on /media/hp-drive failed: Resource busy

----DONE----  sleeping...
```

**Comment by pickonedev** [comment]
I made a completely shutdown after uninstall, then installed again. Worked.
Thanks!
