### ISSUE TITLE
"s6-overlay-suexec: fatal: can only run as pid 1" when starting

### ISSUE THREAD

**Issue by JumpMaster** [adamoutler/HassOSConfigurator#18]
A change in 2022.5 stops this addon from starting.

Full details on the changes can be found here
https://developers.home-assistant.io/blog/2022/05/12/s6-overlay-base-images/

**Comment by pickonedev** [comment]
Same

**Comment by pickonedev** [comment]
I have the same error... Hope it will be fixed...

**Comment by pickonedev** [comment]
@adamoutler , any help, please?

**Comment by adamoutler** [comment]
Please try recent changes.

**Comment by pickonedev** [comment]
Thank you so much, it is working now, but the only problem I have now, is this... (with protection disabled)

```
#############################################################################
###############/config/startup/startup.d/addon_core_samba.sh
###############Container: d9ddc48e0aa5: tmp/addon_core_samba.startup.sh
#############################################################################
mount: mounting /dev/sda1 on /media/hp-drive failed: Permission denied
```

**Comment by adamoutler** [comment]
This is not being actively developed. I'm taking pull requests.  You can install this as a local and rebuild/edit it from the source locally on your HA.

**Comment by avee87** [comment]
Looks like recent `init: false` change only fixed startup.d addon. Shouldn't the same be done to others? I'm actually getting the same error in I2C addon.

**Comment by avee87** [comment]
Just created #19 to hopefully fix it

**Comment by marciogranzotto** [comment]
Same issue on `HossOS SSH port 22222 Configurator`
