### ISSUE TITLE
Running the HassOS SSH port 22222 Configurator I get "no config found" for all devices

### ISSUE THREAD

**Issue by dtwilliamson** [adamoutler/HassOSConfigurator#26]
```
no vda1 config found
no sda1 config found
no sdb1 config found
no mmcblk0p1 config found
no mmcblk1p1 config found
no nvme0n1p1 config found
This Configurator did it's job. Perform a hard-power-off now. This configurator only works once and is no longer needed.
```

This is may be because I have a USB-connected spinning hard disk and no SSD or SD on a Raspberry Pi.

How do I find what the device name should be?

Can you add support for this device? Can you add logic to `run.sh` so it doesn't output the "did its job" message if all devices fail?

Minor nit: there's an extraneous apostrophe - you have "it's" which should be "its".

**Comment by adamoutler** [comment]
You need to disable protection mode

**Comment by dtwilliamson** [comment]
Thanks. That did it. I must have overlooked that in the instructions.
