### ISSUE TITLE
Possible related issue that prevents HASS OS update

### ISSUE THREAD

**Issue by Paxy** [adamoutler/HassOSConfigurator#27]
Take a look at this issue.
It stopped when I deleted Run On Startup.d (0.11a) addon.
https://github.com/home-assistant/operating-system/issues/2215

**Comment by adamoutler** [comment]
Delete the script that runs in home assistant context.

**Comment by agners** [comment]
Maybe worth adding a note in the add-on. People should at least stop the add-on before doing a Core update.

**Comment by Paxy** [comment]
Addon stop did not resolved the issue last time i tried. Probably started script is still running in background.

**Comment by agners** [comment]
In a quick test, a `docker stop` stops a process which I started using `docker exec`. 

Maybe it also depends what your startup script exactly does?

**Comment by Paxy** [comment]
I used that plugin to connect remote HCI Bluetooth device with commands:
```
apk update
apk add linux-tools-usbip
usbip attach --remote=172.16.100.100 --busid=1-7
```

**Comment by agners** [comment]
Hm, I would expect `usbip attach` to do its work and exit and not hold on to any resources, but maybe it does hold on to something?

**Comment by Paxy** [comment]
Not sure, but it's not safe to run in that addon.

**Comment by adamoutler** [comment]
Yes. This addon violates the security model of docker and home assistant.  Due to the open nature of the addon, there's no way to say "it's safe" because it allows you to run anything under any container.
