### ISSUE TITLE
git clone "Repository Not Found"

### ISSUE THREAD

**Issue by tke121** [adamoutler/HassOSConfigurator#28]
Can't add the repository to the HA addons.  Tried running the git clone command outside of HA, and get same error?  However, I can access the repository thru the web browser.

git clone -v --recursive --depth=1 --shallow-submodules https://github.com/adamoutler/HassOSConfigurator/tree/main/Run
Cloning into 'Run'...
fatal: repository 'https://github.com/adamoutler/HassOSConfigurator/tree/main/Run/' not found

Is their a problem with cloning the repository?  Tried this from multiple machines.  They all get "repository not found"

I was able to clone multiple other git repositories as a test......just verifying my git setup seems Ok.

**Comment by adamoutler** [comment]
Add the main repo
