### ISSUE TITLE
Configurator says Protection Mode is enabled but it is disable.

### ISSUE THREAD

**Issue by haforme** [adamoutler/HassOSConfigurator#3]
I'm new at this but have followed your instructions and the "HassOS I2C Configurator" states in the log that the "Detected Protection Mode is enabled. Disable Protection Mode in Info Screen.".  I have it disabled.  I'm running "Home Assistant OS" core-2021.2.2 and your add-on version 0.11a.  I have power cycled twice. Thanks for any help you can provide.

I don't see I2C.
no sda1 available
no sdb1 available
mount: permission denied (are you root?)
Detected Protection Mode is enabled. Disable Protection Mode in Info Screen.
no mmcblk0p1 config found
This Configurator did it's job. Perform a hard-power-off reboot now.
You will need to reboot twice total, once to place the files, and again to activate the I2C.
ls: /dev/i2c-1: No such file or directory

**Comment by adamoutler** [comment]
Are you running HassOS?

**Comment by haforme** [comment]
Yes, 


Version | core-2021.2.2
-- | --
Installation Type | Home Assistant OS

**Comment by adamoutler** [comment]
Looks like it's caused by this https://github.com/home-assistant/supervisor/issues/2590.

**Comment by adamoutler** [comment]
I attempted to resolve with https://github.com/home-assistant/supervisor/pull/2596, but HA declined.

**Comment by iCSpotRun** [comment]
Is there a workaround? I'm struggling with the exact same issue

**Comment by haforme** [comment]
Manual method.
https://www.home-assistant.io/common-tasks/os#enable-i2c 

Trevor

**Comment by iCSpotRun** [comment]
Duh, thank you! It worked :)
