### ISSUE TITLE
[suggestion] RaspController configurator

### ISSUE THREAD

**Issue by Santanachia** [adamoutler/HassOSConfigurator#30]
standard debian allows you to install the necessary repositories that allow you to use [RaspController](https://play.google.com/store/apps/details?id=it.Ettore.raspcontroller&hl=en&gl=US). It would be great if you wrote a plugin that installs the necessary components.

**Comment by adamoutler** [comment]
have you tried just using it with a Terminal & SSH app?

**Comment by Santanachia** [comment]
[RaspController](https://play.google.com/store/apps/details?id=it.Ettore.raspcontroller&hl=en&gl=US) uses additional tools that it tries to install via apt. Unfortunately, there is no apt in HAOS. If the missing stuff was installed by your plugin, then it could connect.

**Comment by adamoutler** [comment]
You should talk to the RaspController dev.  While I think it would be easy enough, it could be done with 2-lines of Dockerfile and a  config, I'm not in this to support someone else's business.  That app has Ads and microtransactions.
