### ISSUE TITLE
ssh configurator: Read-only file system problem

### ISSUE THREAD

**Issue by viseshrp** [adamoutler/HassOSConfigurator#34]
Hello @adamoutler ,

Thank you for the port 22222 configurator. I finally got it working by following this thread here https://community.home-assistant.io/t/add-on-hassos-ssh-port-22222-configurator/264109/291
I installed the Add-on, checked the logs and the ssh keys seemed to be installed correctly. 
I then did `ssh root@192.168.68.88 -p22222` and got in.
I am, however, unable to write anything. 

<img width="514" alt="image" src="https://github.com/adamoutler/HassOSConfigurator/assets/11642379/139139bd-0a14-4e57-98de-66dc3a2d4682">

**Comment by adamoutler** [comment]
Did you disable protection mode?

**Comment by viseshrp** [comment]
Yes

**Comment by viseshrp** [comment]
@adamoutler 

<img width="1083" alt="image" src="https://github.com/adamoutler/HassOSConfigurator/assets/11642379/330c8f9a-034f-4865-a2f3-a2a79ba787d3">

**Comment by adamoutler** [comment]
You have some general system troubleshooting to do.  Ask in the forums.

**Comment by viseshrp** [comment]
What sort of general troubleshooting? Can you attempt to at least help a little bit before prematurely closing issues and dismissing problems?  My hass installation and file system are fine. There are zero other issues. I can edit files via other addons like file editor.
