### ISSUE TITLE
fails with homeassistant container in VM

### ISSUE THREAD

**Issue by mfaber** [adamoutler/HassOSConfigurator#4]
using recent latest versions of HA VM
scripts run fine in all containers (addons, supervisor etc) except for the homeassistant container
Error in logs/homeassistant.log: exec: fatal: unable to exec /tmp/homeassistant.startup.sh: no such file or directory

traced it to /tmp not being mounted with x rights, so docker exec command fails here.
using /media directory for homeassistant container as a workaroung at the moment but would be happy if you could provide a better solution.
not a unix crack myself - if i can still be of assistance or if you need more information i am happy to help
Thanks :)

addition: the docker cp command seems to fail as well as the script does not arrive at the /tmp directory. If i manually copy the script to the home assistants /tmp directory, the docker exec command still fails. If I issue a mount -o remount,exec /tmp on the homeassistant container shell I can then issue the docker exec command and the script runs. After the next reboot, the /tmp diretory is however again in the noexec nowrite status.

**Comment by adamoutler** [comment]
It's a problem with Supervisor container.  Nothing I can do for now.
