### ISSUE TITLE
Run: run.sh line 59 logOption is unbound

### ISSUE THREAD

**Issue by yelvert** [adamoutler/HassOSConfigurator#6]
It looks like the `logOption` variable is only ever getting defined if the `Retain old logs in /config/startup/logs/ instead of deleting old log` config option is true. When that option is false `logOption` should be set to `""` when that config option is false.

**Comment by adamoutler** [comment]
Is this still valid?

**Comment by yelvert** [comment]
Yeah, see line 21 of that run.sh script, the logOption variable only gets created if the test passes, which means if it doesn't pass then anything that references that variable later will throw an error.

**Comment by adamoutler** [comment]
fixed. sorry it took so long.
