### ISSUE TITLE
Installing and running this, left my RPi HA completely useless

### ISSUE THREAD

**Issue by michaelmadsen72** [adamoutler/HassOSConfigurator#7]
After installing this and rebooting several times, I could no longer boot up.
My system is booting from an USB SSD disk (no SD card installed).

**Comment by adamoutler** [comment]
This is 3 separate tools. I assume you did the one for DeskPi Pro to enable the Front USB and the Serial port?  If so, this is expected operation.  You only need serial port for devices which have built in hard disks.
